runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images

- url: /pdfs
  static_dir: pdfs

- url: /.*
  script: main.application

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: latest