#!/usr/bin/env python3

import os
import subprocess
from bs4 import BeautifulSoup

path_web = os.getcwd()
path_conf = os.path.join(path_web, 'scripts/myconfig.cfg')
path_dest = os.path.join(path_web, 'templates/includes/')
path_sh = os.path.join(path_web, 'scripts/generate-html.sh')


def processHTML(path_to_tex):
    """Compile LaTeX file and convert to HTML."""
    # Compile tex file
    subprocess.call([path_sh, path_to_tex, path_conf])

    # Return basename without extension
    path_base = os.path.splitext(os.path.basename(path_to_tex))[0]
    path_dir = os.path.dirname(path_to_tex)  # dirname
    path_to_soup = os.path.join(path_dir, path_base + '.html')

    # Use Python built-in HTML parser
    soup = BeautifulSoup(open(path_to_soup), 'html.parser')

    body_tag = soup.body        # extract body tag

    # <body> --> <div class='latex'>
    body_tag.name = "div"
    body_tag['class'] = 'latex'

    # Delete div tag generated by the LaTeX \maketitle cmd and its
    # contents
    maketitle_tag = soup.find('div', class_="maketitle")
    if maketitle_tag:
        maketitle_tag.decompose()

    weeks = soup.find_all("h4")
    for sec in weeks:
        label = sec.span.string.replace(" ", "")
        sec['id'] = label

    output_file = path_dest + path_base + '.html'
    with open(output_file, 'w+') as f:
        print(body_tag.prettify(), file=f)


path_res = os.path.join(path_web, 'latex/research/research.tex')
path_pubs = os.path.join(path_web, 'latex/my-pubs/my-pubs.tex')

path_sched1 = os.path.join(
    path_web, 'website_data',
    'latex/schedules/schedule_s24_phil255/schedule_s24_phil255.tex')
path_sched2 = os.path.join(
    path_web, 'website_data',
    'latex/schedules/schedule_s24_phil212/schedule_s24_phil212.tex')


# processHTML(path_res)
# processHTML(path_pubs)
processHTML(path_sched1)
processHTML(path_sched2)
